version: '3.9'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: anime-list
    networks:
      - anime
networks:
  anime:
